sudo: required
services:
  - docker
before_install:
  - docker build -t awakenedmind/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true awakenedmind/react-test npm test 

after_success:
  - docker build -t awakenedmind/multi-client ./client
  - docker build -t awakenedmind/multi-nginx ./nginx
  - docker build -t awakenedmind/multi-server ./server
  - docker build -t awakenedmind/multi-worker ./worker
  # Dockerhub TravisCI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push awakenedmind/multi-client
  - docker push awakenedmind/multi-nginx
  - docker push awakenedmind/multi-server
  - docker push awakenedmind/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docke-react
  env: multi-docker
  bucket_name: elasticbeanstalk-us-west-2-208624173923
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
      
