version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' # route 3050 to nginx default port of 80
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # look for dockerfile in ./server
    volumes: 
      - /app/node_modules # exclude node_modules
      - ./server:/app # copy everything in ./server to app directory
    environment: # Docker image defaults for Postgres Image
      - REDIS_HOST=redis # just name of service
      - REDIS_PORT=6379 # default port
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules 
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app